# 1. Системні налаштування Spring Boot та вбудованого сервера
spring.main.web-application-type=servlet
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration
server.port=8080
spring.application.name=guestbook-app

# 2. Налаштування представлення (JSP)
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# 3. ВЛАСНІ (КАСТОМНІ) ПАРАМЕТРИ ДОДАТКА ЗГІДНО ІЗ ЗАВДАННЯМ ЛР4
app.catalog.default-page-size=15
app.catalog.welcome-banner=Лабораторна робота 4: Spring Core & Boot активна!
app.catalog.feature-enabled=true